slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox:
      solver_plugin: solver_plugins::CeresSolver
    mode: mapping
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    minimum_time_interval: 0.5
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 12.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    transform_publish_period: 0.02
    tf_buffer_duration: 30.0
    stack_size_to_use_for_scan_matching_thread: 40000000
    use_scan_matching: true
    enable_interactive_mode: false
