slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox:
      mode: mapping
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /model/mobile_manipulator/scan
    transform_publish_period: 0.05
    tf_buffer_duration: 30.0
    resolution: 0.05
    max_laser_range: 15.0
    minimum_time_interval: 0.2
