<?xml version="1.0" ?>
<robot name="mobile_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Materials -->
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="blue"><color rgba="0.203 0.238 0.285 1"/></material>
  <material name="green"><color rgba="0 0.8 0 1"/></material>
  <material name="grey"><color rgba="0.2 0.2 0.2 1"/></material>
  <material name="red"><color rgba="0.8 0.129 0.133 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>

  <!-- Inertia helper -->
  <xacro:macro name="cylinder_inertia" params="mass r l">
    <inertia ixx="${mass * (3*r*r + l*l) / 12}"
             iyy="${mass * (3*r*r + l*l) / 12}"
             izz="${mass * r*r / 2}"
             ixy="0" ixz="0" iyz="0"/>
  </xacro:macro>

  <!-- Arm properties -->
  <xacro:property name="arm_01_len" value="0.2" />
  <xacro:property name="arm_01_mass" value="0.025" />
  <xacro:property name="arm_02_len" value="0.2" />
  <xacro:property name="arm_02_mass" value="0.025" />
  <xacro:property name="arm_03_len" value="0.2" />
  <xacro:property name="arm_03_mass" value="0.025" />
  <xacro:property name="arm_04_len" value="0.25" />
  <xacro:property name="arm_04_mass" value="0.025" />
  <xacro:property name="offset" value="0" />

  <!-- Root link -->
  <link name="root_link" />
  <joint name="root_joint" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <!-- Base link -->
  <link name="base_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0.1"/>
      <inertia ixx="0.0395416666667" ixy="0" ixz="0" iyy="0.106208333333" iyz="0" izz="0.106208333333"/>
    </inertial>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><box size="0.5 0.3 0.07"/></geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><box size="0.5 0.3 0.07"/></geometry>
      <material name="blue"/>
    </visual>
    <!-- front caster -->
    <collision>
      <origin rpy="0 0 0" xyz="0.2 0 -0.05"/>
      <geometry><sphere radius="0.05"/></geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0.2 0 -0.05"/>
      <geometry><sphere radius="0.05"/></geometry>
      <material name="grey"/>
    </visual>
  </link>

  <!-- Right wheel -->
  <link name="link_right_wheel">
    <inertial>
      <mass value="0.2"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001"/>
    </inertial>
    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry><cylinder length="0.04" radius="0.1"/></geometry>
    </collision>
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry><cylinder length="0.04" radius="0.1"/></geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="joint_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="link_right_wheel"/>
    <origin rpy="0 0 0" xyz="-0.05 0.15 0"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
  </joint>

  <!-- Left wheel -->
  <link name="link_left_wheel">
    <inertial>
      <mass value="0.2"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001"/>
    </inertial>
    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry><cylinder length="0.04" radius="0.1"/></geometry>
    </collision>
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry><cylinder length="0.04" radius="0.1"/></geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="joint_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="link_left_wheel"/>
    <origin rpy="0 0 0" xyz="-0.05 -0.15 0"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
  </joint>

  <!-- Arm base -->
  <joint name="arm_base_to_base" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.085"/>
  </joint>
  <link name="arm_base_link">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.0000416666667" iyy="0.0000416666667" izz="0.0000416666667" iyz="0" ixy="0" ixz="0"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.1 0.1 0.1"/></geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.1 0.1 0.1"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <!-- Arm joints/links -->
  <joint name="arm_joint_01" type="revolute">
    <parent link="arm_base_link"/>
    <child link="arm_link_01"/>
    <origin rpy="0 0 0" xyz="0 0 ${0.05 + offset}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-3.12" upper="3.139" velocity="5"/>
  </joint>
  <link name="arm_link_01">
    <inertial>
      <origin xyz="0 0 ${arm_01_len/2}" rpy="0 0 0" />
      <mass value="${arm_01_mass}"/>
      <xacro:cylinder_inertia mass="${arm_01_mass}" r="0.04" l="${arm_01_len}" />
    </inertial>
    <collision>
      <origin xyz="0 0 ${arm_01_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${arm_01_len}"/></geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${arm_01_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${arm_01_len}"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="arm_joint_02" type="revolute">
    <parent link="arm_link_01"/>
    <child link="arm_link_02"/>
    <origin rpy="0 0 0" xyz="0 0 ${arm_01_len + offset}"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-1.8" upper="1.8" velocity="5"/>
  </joint>
  <link name="arm_link_02">
    <inertial>
      <origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0" />
      <mass value="${arm_02_mass}"/>
      <xacro:cylinder_inertia mass="${arm_02_mass}" r="0.04" l="${arm_02_len}" />
    </inertial>
    <collision>
      <origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${arm_02_len}"/></geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${arm_02_len}"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="arm_joint_03" type="revolute">
    <parent link="arm_link_02"/>
    <child link="arm_link_03"/>
    <origin rpy="0 0 0" xyz="0 0 ${arm_02_len + offset}"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-1.8" upper="1.8" velocity="5"/>
  </joint>
  <link name="arm_link_03">
    <inertial>
      <origin xyz="0 0 ${arm_03_len/2}" rpy="0 0 0" />
      <mass value="${arm_03_mass}"/>
      <xacro:cylinder_inertia mass="${arm_03_mass}" r="0.04" l="${arm_03_len}" />
    </inertial>
    <collision>
      <origin xyz="0 0 ${arm_03_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${arm_03_len}"/></geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${arm_03_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${arm_03_len}"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="arm_joint_04" type="revolute">
    <parent link="arm_link_03"/>
    <child link="arm_link_04"/>
    <origin rpy="0 0 0" xyz="0 0 ${arm_03_len + offset}"/>
    <axis xyz="0 1 0"/>
    <limit effort="10000.0" lower="-1.8" upper="1.8" velocity="5"/>
  </joint>
  <link name="arm_link_04">
    <inertial>
      <origin xyz="0 0 0.04" rpy="0 0 0" />
      <mass value="${arm_04_mass}"/>
      <inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <geometry><box size="0.034 0.2 0.08"/></geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <geometry><box size="0.034 0.2 0.08"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <!-- Gripper -->
  <joint name="right_grip_joint" type="prismatic">
    <parent link="arm_link_04"/>
    <child link="right_grip_link"/>
    <origin rpy="0 0 0" xyz="${0.015 + 0.03} 0.05 0.04"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-0.04" upper="0.035" velocity="6.5"/>
  </joint>
  <link name="right_grip_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
    </inertial>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><box size="0.06 0.02 0.08"/></geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><box size="0.06 0.02 0.08"/></geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="left_grip_joint" type="prismatic">
    <parent link="arm_link_04"/>
    <child link="left_grip_link"/>
    <origin rpy="0 0 0" xyz="${0.015 + 0.03} -0.05 0.04"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" upper="0.04" lower="-0.035" velocity="6.5"/>
  </joint>
  <link name="left_grip_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
    </inertial>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><box size="0.06 0.02 0.08"/></geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry><box size="0.06 0.02 0.08"/></geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- Camera link -->
  <joint name="camera_joint" type="fixed">
    <parent link="arm_link_04"/>
    <child link="camera_link"/>
    <origin xyz="0.05 0 0.04" rpy="0 0 0"/>
  </joint>
  <link name="camera_link">
    <visual>
      <geometry><box size="0.02 0.02 0.02"/></geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry><box size="0.02 0.02 0.02"/></geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Lidar link (mounted on base) -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.18 0 0.15" rpy="0 0 0"/>
  </joint>
  <link name="lidar_link">
    <visual>
      <geometry><cylinder length="0.02" radius="0.03"/></geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><cylinder length="0.02" radius="0.03"/></geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>
  </link>

  <!-- Gazebo systems and sensors -->
  <xacro:include filename="$(find mobile_manipulator_bringup)/urdf/robot.gazebo"/>

</robot>
